Carbuilder/config/routes.rb
Rails.application.routes.draw do
  resources :parts
  resources :cars
  resources :makes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Carbuilder/app/models/car.rb
class Car < ApplicationRecord
  has_and_belongs_to_many :part
  belongs_to :make
  validates: VIN
end

Carbuilder/app/models/cars_make.rb
class CarsMake < ApplicationRecord
  belongs_to :car
  belongs_to :make
end

Carbuilder/app/models/cars_part.rb
class CarsPart < ApplicationRecord
  belongs_to :car
  belongs_to :part
end

Carbuilder/app/models/make.rb
class Make < ApplicationRecord
  has_many :car
end

Carbuilder/app/models/part.rb
class Part < ApplicationRecord
  has_and_belongs_to_many :cars
validates : make, model, part, VIN


end

Carbuilder/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @parts = Part.all
  end

  # GET /cars/new
  def new
    @car = Car.new
    @parts = Part.all
    @makes = Make.all
  end

  # GET /cars/1/edit
  def edit
    @parts = Part.all
    @makes = Make.all
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      for nil; NilClass
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:model, :VIN, :parts_ids => [], :make_id)
    end
end

Carbuilder/app/controllers/makes_controller.rb
class MakesController < ApplicationController
  before_action :set_make, only: [:show, :edit, :update, :destroy]

  # GET /makes
  # GET /makes.json
  def index
    @makes = Make.all
  end

  # GET /makes/1
  # GET /makes/1.json
  def show
  end

  # GET /makes/new
  def new
    @make = Make.new
    @cars = Car.all
  end

  # GET /makes/1/edit
  def edit
    @cars = Car.all
  end

  # POST /makes
  # POST /makes.json
  def create
    @make = Make.new(make_params)

    respond_to do |format|
      if @make.save
        format.html { redirect_to @make, notice: 'Make was successfully created.' }
        format.json { render :show, status: :created, location: @make }
      else
        format.html { render :new }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /makes/1
  # PATCH/PUT /makes/1.json
  def update
    respond_to do |format|
      if @make.update(make_params)
        format.html { redirect_to @make, notice: 'Make was successfully updated.' }
        format.json { render :show, status: :ok, location: @make }
      else
        format.html { render :edit }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makes/1
  # DELETE /makes/1.json
  def destroy
    @make.destroy
    respond_to do |format|
      format.html { redirect_to makes_url, notice: 'Make was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_make
      @make = Make.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def make_params
      params.require(:make).permit(:name, :country, :car_ids => [])
    end
end

Carbuilder/app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
    @cars = Car.all
    @makes = Make.all
  end

  # GET /parts/1/edit
  def edit
    @cars = Car.all
    @makes = Make.all
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:name, :car_ids =>[])
    end
end

Carbuilder/app/helpers/cars_helper.rb
module CarsHelper
end

Carbuilder/app/helpers/makes_helper.rb
module MakesHelper
end

Carbuilder/app/helpers/parts_helper.rb
module PartsHelper
end

Carbuilder/app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :make_ids%><br>
    <%= form.collection_check_boxes(:make_ids, @makes, :id, :name)%>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :VIN %>
    <%= form.number_field :VIN %>
  </div>

  <div class="field">
    <%= form.label :part_ids%><br>
    <%= form.collection_check_boxes(:part_ids, @parts, :id, :name)%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Carbuilder/app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

Carbuilder/app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Vin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.model %></td>
        <td><%= car.VIN %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

Carbuilder/app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

Carbuilder/app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @car.VIN %>
</p>

<ul>
  <% @car.parts.each do |part| %>
    <li><%= part.name %></li>
 <% end %>
</ul>

<ul>
  <% @car.makes.each do |make| %>
    <li><%= make.name %></li>
 <% end %>
</ul>

</ul>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

Carbuilder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarBuilder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Carbuilder/app/views/makes/_form.html.erb
<%= form_with(model: make, local: true) do |form| %>
  <% if make.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(make.errors.count, "error") %> prohibited this make from being saved:</h2>

      <ul>
      <% make.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :car_ids%><br>
    <%= form.collection_check_boxes(:car_ids, @parts, :id, :model)%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Carbuilder/app/views/makes/edit.html.erb
<h1>Editing Make</h1>

<%= render 'form', make: @make %>

<%= link_to 'Show', @make %> |
<%= link_to 'Back', makes_path %>

Carbuilder/app/views/makes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Makes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @makes.each do |make| %>
      <tr>
        <td><%= make.name %></td>
        <td><%= make.country %></td>
        <td><%= link_to 'Show', make %></td>
        <td><%= link_to 'Edit', edit_make_path(make) %></td>
        <td><%= link_to 'Destroy', make, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Make', new_make_path %>

Carbuilder/app/views/makes/new.html.erb
<h1>New Make</h1>

<%= render 'form', make: @make %>

<%= link_to 'Back', makes_path %>

Carbuilder/app/views/makes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @make.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @make.country %>
</p>

<ul>
  <% @car.makes.each do |make| %>
    <li><%= make.name %></li>
 <% end %>
</ul>

<ul>
  <% @make.car.each do |car| %>
    <li><%= c.name %></li>
 <% end %>
</ul>

<%= link_to 'Edit', edit_make_path(@make) %> |
<%= link_to 'Back', makes_path %>

Carbuilder/app/views/parts/_form.html.erb
<%= form_with(model: part, local: true) do |form| %>
  <% if part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Carbuilder/app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

Carbuilder/app/views/parts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td><%= part.name %></td>
        <td><%= link_to 'Show', part %></td>
        <td><%= link_to 'Edit', edit_part_path(part) %></td>
        <td><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
  <a href="/cars">See Cars</a>|
<br>

<%= link_to 'New Part', new_part_path %>

Carbuilder/app/views/parts/new.html.erb
<h1>New Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Back', parts_path %>

Carbuilder/app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @part.name %>
</p>

<ul>
  <% @part.cars.each do |car| %>
    <li><%= car.model %></li>
 <% end %>
</ul>

<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>